AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true
  ForceEqualSignAlignment: false

Layout/SpaceAroundOperators:
  Enabled: false
  AllowForAlignment: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  IndentationWidth: 2

Style/HashSyntax:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 100
  IgnoredPatterns:
   - '^\s*#.*$'

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Documentation:
  Enabled: false